# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/sm6150-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter courbet davinci mojito phoenix sweet surya toco tucana,$(TARGET_DEVICE)),)

endif
